// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw10.Data;

#nullable disable

namespace cw10.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517182708_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cw10.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "A",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 1,
                            Description = "10920X, 3.5GHz, Socket 2066, 12 cores, 20MB cache",
                            Id = 0,
                            Name = "Intel Core i9"
                        },
                        new
                        {
                            Code = "B",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 2,
                            Description = "XT Prime 16GB OC",
                            Id = 0,
                            Name = "Asus Radeon RX 9070"
                        },
                        new
                        {
                            Code = "C",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "32GB DDR4, 2666MHz, 9th gen, 260-pin SO-DIMM",
                            Id = 0,
                            Name = "MSI Trident 3"
                        });
                });

            modelBuilder.Entity("cw10.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Asus",
                            FoundationDate = new DateTime(1989, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "ASUSTeK Computer Inc."
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "Razer",
                            FoundationDate = new DateTime(1998, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Razer Inc."
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MSI",
                            FoundationDate = new DateTime(1986, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Micro-Star International Co., Ltd"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        });
                });

            modelBuilder.Entity("cw10.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("cw10.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pc",
                            Stock = 5,
                            Warranty = 2,
                            Weight = 5.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Notebook",
                            Stock = 2,
                            Warranty = 1,
                            Weight = 2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultrabook",
                            Stock = 15,
                            Warranty = 1,
                            Weight = 3.6f
                        });
                });

            modelBuilder.Entity("cw10.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PcId = 2,
                            ComponentCode = "C",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "A",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "A",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "B",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("cw10.Entities.Component", b =>
                {
                    b.HasOne("cw10.Entities.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Component")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cw10.Entities.ComponentType", "ComponentType")
                        .WithMany("Component")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("cw10.Entities.PcComponent", b =>
                {
                    b.HasOne("cw10.Entities.Component", "Component")
                        .WithMany("PcComponent")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cw10.Entities.Pc", "Pc")
                        .WithMany("PcComponent")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("cw10.Entities.Component", b =>
                {
                    b.Navigation("PcComponent");
                });

            modelBuilder.Entity("cw10.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Component");
                });

            modelBuilder.Entity("cw10.Entities.ComponentType", b =>
                {
                    b.Navigation("Component");
                });

            modelBuilder.Entity("cw10.Entities.Pc", b =>
                {
                    b.Navigation("PcComponent");
                });
#pragma warning restore 612, 618
        }
    }
}
